### ISSUE TITLE
Undefined method 'marked_for_destruction?' after update the last commit

### ISSUE THREAD

**Issue by sshajith** [ryanb/nested_form#195]
pls check the last commit. it is not working with rails 3.2.3.

**Comment by Dorian** [comment]
Unrelated but I came here because this happened to me when using `belongs_to` and `lookup_for` with the lookup_by gem: https://github.com/companygardener/lookup_by
